### ISSUE TITLE
Mixed-up About Section

### ISSUE THREAD

**Issue by simonschoe** [Mixtape-Sessions/Machine-Learning#2]
Hi there,

thank you so much for opensourcing the materials! I guess the `about` information aren't correct, are they?

Best,
Simon

**Comment by kylebutts** [comment]
Thank you! Fixed it

**Comment by scunning1975** [comment]
Thank you kyle !Sent from my iPhoneOn Dec 28, 2022, at 8:03 AM, Kyle F Butts ***@***.***> wrote:﻿
Thank you! Fixed it
